import { commonIcons, dashboardIcons } from "@/assets";
import type { IconName } from "@/components/ui/custom/icon";
export type MentaDataTypeProps = {
    [key: string]: {
        title: string;
        path: string;
        icon?: IconName;
        image?: string;
        animetedImage?: string;
        isVisible?: boolean;
        borderAnimation?: boolean;
        borderColor?: string;
        iconFillColor?: string;
        iconStrokeColor?: string;
        backgroundColor?: string;
        borderRadius?: number;
        padding?: number;
        width?: number;
        height?: number;
        breadcrumbItems?: { id: number; label: string }[];
    };
};
export const metadata: MentaDataTypeProps = {
    dashboard: {
        title: "Dashboard",
        icon: "LayoutDashboard",
        path: "/"
    },
    profile: {
        title: "dashboard.profile.title",
        image: dashboardIcons.profileIcon,
        animetedImage: dashboardIcons.profileIcon,
        path: "/profile",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border border-border-accent",
        iconFillColor: "success",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "header.UserProfile" },
        ],

    },
    booking: {
        title: "dashboard.bookings.title",
        image: dashboardIcons.bookIcon,
        animetedImage: dashboardIcons.bookIcon,
        path: "/bookings",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "header.BookingHistory" },
        ],
    },
    notice: {
        title: "dashboard.notices.title",
        image: dashboardIcons.messageIcon,
        animetedImage: dashboardIcons.messageIcon,
        path: "/notices",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "header.UniversityNotices" },
        ],
    },
    seatBooking: {
        title: "dashboard.reserveSeatAndPC.title",
        image: dashboardIcons.seatIcon,
        animetedImage: dashboardIcons.seatIcon,
        path: "/seat-booking",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "roomLayout.generalRoom" },
        ],
    },
    seatBookingPage: {
        title: "Seat Booking",
        path: "/seat-booking-page",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "roomLayout.generalRoom" },
            { id: 3, label: "header.SeatSelection" },

        ],
    },
    groupBooking: {
        title: "dashboard.reserveGroup.title",
        image: dashboardIcons.groupIcon,
        animetedImage: dashboardIcons.groupIcon,
        path: "/group-bookings",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "roomLayout.groupStudyRoom" },

        ],
    },
    timeSelection: {
        title: "Group Bookings",
        path: "/time-selection",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "roomLayout.groupStudyRoom" },
            { id: 2, label: "header.DisplayTimeChart" },

        ],
    },
    reservaton: {
        title: "Group Bookings",
        path: "/reservation",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "roomLayout.groupStudyRoom" },
            { id: 3, label: "header.DisplayTimeChart" },
            { id: 4, label: "header.TimeAndUserPicker" },


        ],
    },
    carrelBooking: {
        title: "dashboard.reserveCarrel.title",
        image: dashboardIcons.carrelIcon,
        animetedImage: dashboardIcons.carrelIcon,
        path: "/carrel-booking",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "roomLayout.personalCarrel" },

        ],
    },
    carrelTimeSelection: {
        title: "Carrel Booking",
        path: "/carrel-time-selection",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "roomLayout.personalCarrel" },
            { id: 2, label: "header.DisplayTimeChart" },

        ],
    },
    message: {
        title: "dashboard.push.title",
        image: commonIcons.bellIcon,
        animetedImage: dashboardIcons.bellIcon,
        path: "/messages",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "header.PushNotifications" },

        ],
    },
    bookSearch: {
        title: "dashboard.bookSearch.title",
        image: dashboardIcons.bookLoanIcon,
        animetedImage: dashboardIcons.bookLoanIcon,
        path: "/book-search",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
    },
    bookPurchase: {
        title: "dashboard.bookRequest.title",
        image: dashboardIcons.bookRequestIcon,
        animetedImage: dashboardIcons.bookRequestIcon,
        path: "/book-purchase",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
    },
    loanHistory: {
        title: "dashboard.loanHistory.title",
        image: dashboardIcons.loanHistoryIcon,
        animetedImage: dashboardIcons.loanHistoryIcon,
        path: "/loan-history",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
    },
    eBook: {
        title: "E-Books",
        image: dashboardIcons.eBookIcon,
        animetedImage: dashboardIcons.eBookIcon,
        path: "/e-books",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
    },
    setting: {
        title: "dashboard.appSettings.title",
        image: dashboardIcons.settingIcon,
        animetedImage: dashboardIcons.settingIcon,
        path: "/settings",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "header.Settings" },
        ],
    },
    PreferredSeatSetting: {
        title: "Settings",
        path: "/settings-preferred-seat",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "header.FavouriteSeat" },
        ],
    },
        oneDayPass: {
        title: "One Day Pass",
        path: "/one-day-pass",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
       
    },
    login: {
        title: "Login",
        image: "KeyRound",
        path: "/login",

    },
}