import { commonIcons, dashboardIcons } from "@/assets";
import type { IconName } from "@/components/ui/custom/icon";
export type MentaDataTypeProps = {
    [key: string]: {
        title: string;
        path: string;
        icon?: IconName;
        image?: string;
        animetedImage?: string;
        isVisible?: boolean;
        borderAnimation?: boolean;
        borderColor?: string;
        iconFillColor?: string;
        iconStrokeColor?: string;
        backgroundColor?: string;
        borderRadius?: number;
        padding?: number;
        width?: number;
        height?: number;
        breadcrumbItems?: { id: number; label: string }[];
    };
};
export const metadata: MentaDataTypeProps = {
    dashboard: {
        title: "Dashboard",
        icon: "LayoutDashboard",
        path: "/"
    },
    profile: {
        title: "My Profile",
        image: dashboardIcons.profileIcon,
        animetedImage: dashboardIcons.profileIcon,
        path: "/profile",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border border-border-accent",
        iconFillColor: "success",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "Dashboard" },
            { id: 2, label: "Profile" },
        ],

    },
    booking: {
        title: "My Bookings",
        image: dashboardIcons.bookIcon,
        animetedImage: dashboardIcons.bookIcon,
        path: "/bookings",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "Dashboard" },
            { id: 2, label: "Bookings" },
        ],
    },
    notice: {
        title: "Notices",
        image: dashboardIcons.messageIcon,
        animetedImage: dashboardIcons.messageIcon,
        path: "/notices",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "Dashboard" },
            { id: 2, label: "University Notices" },
        ],
    },
    seatBooking: {
        title: "Seat Booking",
        image: dashboardIcons.seatIcon,
        animetedImage: dashboardIcons.seatIcon,
        path: "/seat-booking",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "Dashboard" },
            { id: 2, label: "General/PC Seat" },
        ],
    },
    seatBookingPage: {
        title: "Seat Booking",
        path: "/seat-booking-page",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "Dashboard" },
            { id: 2, label: "General/PC Seat" },
            { id: 3, label: "Seat Booking" },

        ],
    },
    groupBooking: {
        title: "Group Bookings",
        image: dashboardIcons.groupIcon,
        animetedImage: dashboardIcons.groupIcon,
        path: "/group-bookings",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "Dashboard" },
            { id: 2, label: "Group Study" },

        ],
    },
    timeSelection: {
        title: "Group Bookings",
        path: "/time-selection",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "Dashboard" },
            { id: 2, label: "Group Study" },
            { id: 2, label: "Time Selection" },

        ],
    },
    reservaton: {
        title: "Group Bookings",
        path: "/reservation",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "Dashboard" },
            { id: 2, label: "Group Study" },
            { id: 3, label: "Time Selection" },
            { id: 4, label: "Reservation" },


        ],
    },
    carrelBooking: {
        title: "Carrel Booking",
        image: dashboardIcons.carrelIcon,
        animetedImage: dashboardIcons.carrelIcon,
        path: "/carrel-booking",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "Dashboard" },
            { id: 2, label: "Personal Carrel" },

        ],
    },
     carrelTimeSelection: {
        title: "Carrel Booking",
        path: "/carrel-time-selection",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "Dashboard" },
            { id: 2, label: "Personal Carrel" },
            { id: 2, label: "Time Selection" },

        ],
    },
    message: {
        title: "Messages",
        image: commonIcons.bellIcon,
        animetedImage: dashboardIcons.bellIcon,
        path: "/messages",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "Dashboard" },
            { id: 2, label: "Notifications" },

        ],
    },
    bookSearch: {
        title: "Book Search",
        image: dashboardIcons.bookLoanIcon,
        animetedImage: dashboardIcons.bookLoanIcon,
        path: "/book-search",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
    },
    bookPurchase: {
        title: "Book Purchase",
        image: dashboardIcons.bookRequestIcon,
        animetedImage: dashboardIcons.bookRequestIcon,
        path: "/book-purchase",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
    },
    loanHistory: {
        title: "Loan History",
        image: dashboardIcons.loanHistoryIcon,
        animetedImage: dashboardIcons.loanHistoryIcon,
        path: "/loan-history",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
    },
    eBook: {
        title: "E-Books",
        image: dashboardIcons.eBookIcon,
        animetedImage: dashboardIcons.eBookIcon,
        path: "/e-books",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
    },
    setting: {
        title: "Settings",
        image: dashboardIcons.settingIcon,
        animetedImage: dashboardIcons.settingIcon,
        path: "/settings",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "Dashboard" },
            { id: 2, label: "Settings" },
        ],
    },
    PreferredSeatSetting: {
        title: "Settings",
        path: "/settings-preferred-seat",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "Dashboard" },
            { id: 2, label: "Favourite Seat" },
        ],
    },
    login: {
        title: "Login",
        image: "KeyRound",
        path: "/login",

    },
}