import { commonIcons, dashboardIcons } from "@/assets";
import type { IconName } from "@/components/ui/custom/icon";
export type MentaDataTypeProps = {
    [key: string]: {
        title: string;
        path: string;
        queryParams?: string;
        icon?: IconName;
        image?: string | React.ComponentType<any>;
        animetedImage?: string | React.ComponentType<any>;
        isVisible?: boolean;
        borderAnimation?: boolean;
        borderColor?: string;
        iconFillColor?: string;
        iconStrokeColor?: string;
        backgroundColor?: string;
        borderRadius?: number;
        padding?: number;
        width?: number;
        height?: number;
        breadcrumbItems?: { id: number; label: string }[];
        isExternal?: boolean;
        requiresSecret?: boolean;
        externalUrl?: (secret?: string) => string;
    };
};
export const metadata: MentaDataTypeProps = {
    dashboard: {
        title: "Dashboard",
        icon: "LayoutDashboard",
        path: "/"
    },
    profile: {
        title: "dashboard.profile.title",
        image: dashboardIcons.ProfileIcon,
        animetedImage: dashboardIcons.ProfileIcon,
        path: "/profile",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border border-border-accent",
        iconFillColor: "success",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "header.UserProfile" },
        ],

    },
    booking: {
        title: "dashboard.bookings.title",
        image: dashboardIcons.BookIcon,
        animetedImage: dashboardIcons.BookIcon,
        path: "/bookings",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "header.BookingHistory" },
        ],
    },
    notice: {
        title: "dashboard.notices.title",
        image: dashboardIcons.MessageIcon,
        animetedImage: dashboardIcons.MessageIcon,
        path: "/notices",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "header.UniversityNotices" },
        ],
    },
    seatBooking: {
        title: "dashboard.reserveSeatAndPC.title",
        image: dashboardIcons.SeatIcon,
        animetedImage: dashboardIcons.SeatIcon,
        path: "/ticketing/RoomSelection",
        queryParams: "?catCodes=401,402&hideFloor=true&hideCategory=true",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "roomLayout.generalRoom" },
        ],
    },
    seatBookingPage: {
        title: "Seat Booking",
        path: "/seat-booking-page",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "roomLayout.generalRoom" },
            { id: 3, label: "header.SeatSelection" },

        ],
    },
    groupBooking: {
        title: "dashboard.reserveGroup.title",
        image: dashboardIcons.GroupIcon,
        animetedImage: dashboardIcons.GroupIcon,
        path: "/ticketing/RoomSelection",
        queryParams: "?catCodes=403&hideFloor=true",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "roomLayout.groupStudyRoom" },

        ],
    },
    timeSelection: {
        title: "Group Bookings",
        path: "/time-selection",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "roomLayout.groupStudyRoom" },
            { id: 2, label: "header.DisplayTimeChart" },

        ],
    },
    reservaton: {
        title: "Group Bookings",
        path: "/reservation",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "roomLayout.groupStudyRoom" },
            { id: 3, label: "header.DisplayTimeChart" },
            { id: 4, label: "header.TimeAndUserPicker" },


        ],
    },
    carrelBooking: {
        title: "dashboard.reserveCarrel.title",
        image: dashboardIcons.CarrelIcon,
        animetedImage: dashboardIcons.CarrelIcon,
        path: "/ticketing/RoomSelection",
        queryParams: "?catCodes=404&hideFloor=true",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "roomLayout.personalCarrel" },

        ],
    },
    carrelTimeSelection: {
        title: "Carrel Booking",
        path: "/carrel-time-selection",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "roomLayout.personalCarrel" },
            { id: 2, label: "header.DisplayTimeChart" },

        ],
    },
    // Ticketing System Routes
    ticketingRoomSelection: {
        title: "Room Selection",
        path: "/ticketing/RoomSelection",
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "Room Selection" },
        ],
    },
    ticketingSeatSelection: {
        title: "Seat Selection",
        path: "/ticketing/SeatSelection",
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "Room Selection" },
            { id: 3, label: "header.SeatSelection" },
        ],
    },
    ticketingDisplayTimeChart: {
        title: "Time Chart",
        path: "/ticketing/DisplayTimeChart",
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "Room Selection" },
            { id: 3, label: "header.DisplayTimeChart" },
        ],
    },
    ticketingTimeAndUserPicker: {
        title: "Time & User Picker",
        path: "/ticketing/TimeAndUserPicker",
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "Room Selection" },
            { id: 3, label: "header.DisplayTimeChart" },
            { id: 4, label: "header.TimeAndUserPicker" },
        ],
    },
    message: {
        title: "dashboard.push.title",
        image: commonIcons.BellIcon,
        animetedImage: dashboardIcons.BellIcon,
        path: "/messages",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "header.PushNotifications" },

        ],
    },
    bookSearch: {
        title: "dashboard.bookSearch.title",
        image: dashboardIcons.BookLoanIcon,
        animetedImage: dashboardIcons.BookLoanIcon,
        path: "/book-search",
        externalUrl: (kmouSecretSecret?: string) => `https://library.kmou.ac.kr/appLogin?encText=${kmouSecretSecret}&retUrl=/searchTotal/result?st=KWRD%26si=TOTAL%26q=`,
        isExternal: true,
        requiresSecret: true,
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
    },
    bookPurchase: {
        title: "dashboard.bookRequest.title",
        image: dashboardIcons.BookRequestIcon,
        animetedImage: dashboardIcons.BookRequestIcon,
        path: "/book-purchase",
        externalUrl: (kmouSecretSecret?: string) => `https://library.kmou.ac.kr/appLogin?encText=${kmouSecretSecret}&retUrl=/webcontent/info/13`,
        isExternal: true,
        requiresSecret: true,
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
    },
    loanHistory: {
        title: "dashboard.loanHistory.title",
        image: dashboardIcons.LoanHistoryIcon,
        animetedImage: dashboardIcons.LoanHistoryIcon,
        path: "/loan-history",
        externalUrl: (kmouSecretSecret?: string) => `https://library.kmou.ac.kr/appLogin?encText=${kmouSecretSecret}&retUrl=/myloan/list`,
        isExternal: true,
        requiresSecret: true,
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
    },
    eBook: {
        title: "dashboard.eBook.title",
        image: dashboardIcons.EBookIcon,
        animetedImage: dashboardIcons.EBookIcon,
        path: "/e-books",
        externalUrl: (kmouSecretSecret?: string) => `https://library.kmou.ac.kr/appLogin?encText=${kmouSecretSecret}&retUrl=/webcontent/info/72`,
        isExternal: true,
        requiresSecret: true,
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
    },
    setting: {
        title: "dashboard.appSettings.title",
        image: dashboardIcons.SettingIcon,
        animetedImage: dashboardIcons.SettingIcon,
        path: "/settings",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "header.Settings" },
        ],
    },
    PreferredSeatSetting: {
        title: "Settings",
        path: "/settings-preferred-seat",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
        breadcrumbItems: [
            { id: 1, label: "header.dashboard" },
            { id: 2, label: "header.FavouriteSeat" },
        ],
    },
        oneDayPass: {
        title: "One Day Pass",
        path: "/one-day-pass",
        isVisible: true,
        borderAnimation: false,
        borderColor: "border-accent",
        iconFillColor: "primary-400",
        iconStrokeColor: "border-accent",
        backgroundColor: "background",
        borderRadius: 16,
        padding: 12,
        width: 38,
        height: 38,
       
    },
    login: {
        title: "Login",
        image: "KeyRound",
        path: "/login",

    },
}
